### ISSUE TITLE
errors/update in documentation

### ISSUE THREAD

**Issue by PhilLAL** [tango-controls/PyTangoArchiving#5]
Hi Sergi,
reading https://github.com/tango-controls/PyTangoArchiving/blob/master/README.rst I noticed that link http://www.tango-controls.org/resources/howto/pytangoarchiving is dead.
Regards

**Comment by jcmarrucho** [comment]
Hi Sergi,
i suggest this link : http://tango-controls.readthedocs.io/en/latest/tutorials-and-howtos/how-tos/how-to-pytangoarchiving.html
Regards,
JCM

**Comment by sergirubio** [comment]
Thanks
