### ISSUE TITLE
TaurusAttributeChooser missing .ui file

### ISSUE THREAD

**Issue by amilan** [tango-controls/PyTangoArchiving#6]
Hi, 

I'm trying to use the snaps widgets. 
I've found a couple of issues that I manage to solve (I can create a PR when everything will be working) but now I've found that when using the snaps widget, if one tries to create a new context, it fails because it's expecting to have a .ui/TaurusAttributeChooser.ui file that it's not present.

**Comment by jcmarrucho** [comment]
Hi,
i have the same problem using snaps.py
Able to read the snapshots but unable to create a new context.
Missing TaurusAttributeChooser.ui

**Comment by sergirubio** [comment]
Hi,

The problem with this file was that it was removed from the Taurus package.

I'll search for it in Taurus3 repo and add it to PyTangoArchiving

Sorry, I'll have to do it tomorrow as I'm on medical leave

Sergi

**Comment by jcmarrucho** [comment]
Hi Sergi,

this file is still missing in recent versions:
PyTangoArchiving 8.3.1
taurus 4.4.0

thanks.

**Comment by amilan** [comment]
Hi,
I have created a PR with the missing file, plus some modifications needed at MaxIV to make the gui work.

The PR is: #10

**Comment by sergirubio** [comment]
Many thanks Antonio!, Sorry for not solving this before
